### ISSUE TITLE
Possible to shorten time command is sent?

### ISSUE THREAD

**Issue by mnblah** [leedave/flipper-zero-cross-remote#1]
Any chance you can shorten the time a command is sent over IR, or maybe give the option of a default duration?  I've been having issues running commands, like up and down, to try and scroll through menus.

**Comment by leedave** [comment]
Thank you for the input. 

I made an easy & fast solution. The setting is global, so not related to single command chains or even single signals. 

I've added a setting to control the time an IR signal is sent (default is 1000ms). Now it is possible to reduce or extend by 100ms until 0 or 2900ms. I think that should be enough for what you need. 

The code is updated here, I've also send a request to update it in the Flipper Application Catalog (mobile app). 
Hope that helps ;)

**Comment by mavols** [comment]
> Thank you for the input.
> 
> I made an easy & fast solution. The setting is global, so not related to single command chains or even single signals.
> 
> I've added a setting to control the time an IR signal is sent (default is 1000ms). Now it is possible to reduce or extend by 100ms until 0 or 2900ms. I think that should be enough for what you need.
> 
> The code is updated here, I've also send a request to update it in the Flipper Application Catalog (mobile app). Hope that helps ;)

it would be nice to put this feature for each button. 
for example by default it is 1000ms, but if needed you can adjust for each button this time.

i need to adjust brightness on tv to 0. to do this I need to click as fast as possible (200ms) menu setting but in the end when brightness adjustment started I need to hold arrow to the left (2900ms) to move it completely down. 

so my macros could be like this:
(IR function) menu button(200ms)-right arrow(200ms)-down arrow(200ms)-ok button(200ms)-left arrow(2900ms)-menu button(200ms)

is it possible to do that?

**Comment by leedave** [comment]
That would take some work. I'll think about it. A definite downside would be that I will need to refactor the file format, so any old recordings could break.

**Comment by leedave** [comment]
Feature is planned. Preparations are made in the current build, but the feature will unlock in a release shortly after the next one.

**Comment by leedave** [comment]
Feature is now available with in version 2.1. 

Note:
It may take a while until available in Official App Catalog, as there is a conflict in the uFBT compiling that flipper devs are looking into. So until available there, you'll need to compile the app or get it in my faps repository.
