### ISSUE TITLE
IR Commands Max Length

### ISSUE THREAD

**Issue by HyeonJaeKim** [leedave/flipper-zero-cross-remote#24]
Hello,

I'm trying to use this app to brute force my device's pin number (0000-9999) but the flipper zero freezes if I make the IR playlist file too big.

Do you know what the max size of a IR playlist can be? I am going to split up the big playlist into multiple smaller playlists but it would be helpful to know how many times to divide it by.

**Comment by leedave** [comment]
That's a difficult question, as many of the attributes vary. Size of your commands, RAM used by system etc. And it's not the actual intention of the app that you are using this for. 

Generally the Flipper has 256kb of RAM. As a rule of thumb, half will be used by the System. So your file shouldn't be more than 128kb, but as you never know how much the system currently occupies, you should have a buffer left. 

The other thing is that all IR commands chained in my app are stored into the *.xr file you save. So keep in mind, all your commands you want to chain are in one file. This could be sub-optimal if you want to brute force something. 

I'm not sure, but I think Flipper doesn't load files to RAM, instead just uses a pointer to reference the current reading point. 

I can only guess, so I'd say start with chunks of max. 64kb.
