### ISSUE TITLE
Can't find saved commands

### ISSUE THREAD

**Issue by dot-Justin** [leedave/flipper-zero-cross-remote#5]
Hey there, loving this so far, it's just what I needed. However, I can't seem to find my saved commands. When I set a name, it takes me back to the command setup page, and doesn't seem to actually save anything. I'm hoping this is a PEBKAC issue, haha.

**Comment by dot-Justin** [comment]
Just tried again, and it took me to the cross remote home page (displaying "New Command Chain", "Run Saved Command", etc) and it did save my command chain. I can't recreate my initial issue, so I'll close this.

**Comment by Whitecx** [comment]
I had a similar issue. The first command chain I saved didn't appear in the list initially. But once I tried to create and save a second command chain, both showed up as expected.
